services:
  # Cassandra Nodes
  seed-node:
    image: cassandra
    container_name: seed-node
    networks:
      - cassandra-sensor-network
    ports:
      - "7199:7199"
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
      CASSANDRA_NUM_TOKENS: 256

  node1:
    image: cassandra
    container_name: node1
    networks:
      - cassandra-sensor-network
    ports:
        - "7202:7199"
        - "9045:9042"
    environment:
      CASSANDRA_SEEDS: seed-node
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"

  node2:
    image: cassandra
    container_name: node2
    networks:
      - cassandra-sensor-network
    ports:
      - "7200:7199" # Avoid conflicts with 7199
      - "9043:9042"
    environment:
      CASSANDRA_SEEDS: seed-node
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"

  node3:
    image: cassandra
    container_name: node3
    networks:
      - cassandra-sensor-network
    ports:
      - "7201:7199"
      - "9044:9042"
    environment:
      CASSANDRA_SEEDS: seed-node
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
  
  zookeeper-node:
    image: bitnami/zookeeper
    container_name: zookeeper-node
    networks:
      - cassandra-sensor-network
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  
  kafka-node:
    image: bitnami/kafka
    container_name: kafka-node
    networks:
      - cassandra-sensor-network
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-node:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "kafka-topic:1:1"

  prometheus-node:
    image: prom/prometheus
    container_name: prometheus-node
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus-node
    networks:
      - cassandra-sensor-network
    ports:
      - "9090:9090"
  
  grafana-node:
    image: grafana/grafana
    container_name: grafana-node
    ports:
      - "3000:3000"
    networks:
      - cassandra-sensor-network
    depends_on:
      - prometheus-node
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


networks:
  cassandra-sensor-network:
    driver: bridge

volumes:
  prometheus_data:

# kafka-topics.sh --create --topic kafka-topic  --bootstrap-server kafka-node:9092
# kafka-topics.sh --list --bootstrap-server localhost:9092